### ISSUE TITLE
Add support for mysql-client 9.0

### ISSUE THREAD

**Issue by SergioBenitez** [sgrif/mysqlclient-sys#53]
It looks like there's no support for identifying mysql-client 9.0, [released today](https://dev.mysql.com/doc/relnotes/mysql/9.0/en/). This is causing [build failures](https://github.com/rwf2/Rocket/actions/runs/10295645452/job/28495652182), which can be overcome by pinning the mysql version. Would be great to support the latest release, however!

**Comment by weiznich** [comment]
I'm happy to accept a PR for that, otherwise this is currently expected behavior as the libmysqlclient headers change in a incompatible way between versions. That means we cannot just allow future versions without having checked that they are compatible in any way or at least without providing some compatibility layer.

**Comment by weiznich** [comment]
I just noticed that it might be helpful to write down what needs to be done:

* Use the rust docker image and install the new mysql-client version there
* Install bindgen in the docker image
* Use https://github.com/sgrif/mysqlclient-sys/blob/master/DEVELOPMENT.md to generate bindings for the various supported targets (need to install the right cross compiler for these targets as well)
* Adjust the build script here to handle the new version: https://github.com/sgrif/mysqlclient-sys/blob/4f9afd960779b463e05363279678da56f025015c/build.rs#L118-L217
* Optionally updating the submodule in mysqlclient-src to use the new release (I would strongly prefer having that in a separate PR)
